"""License registry: provenance for every asset that reaches a customer deliverable.

Two rules drive this module:

1. Nothing ships in a dataset without a recorded source, owner, and license. That
   includes procedurally generated assets, where the honest answer is "generated by
   BladeForge code, no third-party asset embedded".
2. BladeForge never claims ownership of a customer upload. A customer model, HDRI, or
   reference image is owned by the customer, and the customer has to confirm they hold
   the rights before it is accepted.

``build_licenses_manifest`` produces the ``licenses.json`` that goes into every dataset
ZIP, assembled from the registry entries the job actually used.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .versioning import LicenseRecord, checksum

ASSET_BLADE_MODEL = "blade_model"
ASSET_CUSTOMER_MODEL = "customer_model"
ASSET_MATERIAL = "material"
ASSET_TEXTURE = "texture"
ASSET_HDRI = "hdri"
ASSET_ENVIRONMENT = "environment"
ASSET_REFERENCE_IMAGE = "reference_image"
ASSET_CAMERA_PRESET = "camera_preset"
ASSET_DEFECT_PROFILE = "defect_profile"
ASSET_TAXONOMY = "taxonomy"

ASSET_KINDS = (
    ASSET_BLADE_MODEL,
    ASSET_CUSTOMER_MODEL,
    ASSET_MATERIAL,
    ASSET_TEXTURE,
    ASSET_HDRI,
    ASSET_ENVIRONMENT,
    ASSET_REFERENCE_IMAGE,
    ASSET_CAMERA_PRESET,
    ASSET_DEFECT_PROFILE,
    ASSET_TAXONOMY,
)

REVIEW_PENDING = "pending"
REVIEW_APPROVED = "approved"
REVIEW_REJECTED = "rejected"
REVIEW_CUSTOMER_ATTESTED = "customer_attested"
REVIEW_STATUSES = (REVIEW_PENDING, REVIEW_APPROVED, REVIEW_REJECTED, REVIEW_CUSTOMER_ATTESTED)


@dataclass(frozen=True)
class AssetLicense:
    """One licensed asset, identified by kind, id, version, and content checksum."""

    asset_kind: str
    asset_id: str
    asset_version: str
    record: LicenseRecord
    content_checksum: str | None = None
    storage_path: str | None = None

    def __post_init__(self) -> None:
        if self.asset_kind not in ASSET_KINDS:
            raise ValueError(f"Unknown asset kind {self.asset_kind!r}")
        if self.record.review_status not in REVIEW_STATUSES:
            raise ValueError(f"Unknown review status {self.record.review_status!r}")

    @property
    def is_usable(self) -> bool:
        """Whether this asset may be used in a commercial deliverable."""
        return (
            self.record.review_status in {REVIEW_APPROVED, REVIEW_CUSTOMER_ATTESTED}
            and self.record.allows_commercial_use
        )

    def as_dict(self) -> dict[str, Any]:
        return {
            "asset_kind": self.asset_kind,
            "asset_id": self.asset_id,
            "asset_version": self.asset_version,
            "content_checksum": self.content_checksum,
            "storage_path": self.storage_path,
            "is_usable": self.is_usable,
            **self.record.as_dict(),
        }


def customer_owned_license(
    *,
    customer_name: str,
    attested: bool,
    asset_description: str,
    license_name: str = "Customer-owned, not redistributed by BladeForge",
) -> LicenseRecord:
    """The license record for anything a customer uploads.

    ``attested`` records that the customer confirmed they hold the rights. Without that
    confirmation the asset stays pending and cannot be used in a render.
    """
    return LicenseRecord(
        source="customer_upload",
        owner=customer_name,
        license_name=license_name,
        allows_commercial_use=attested,
        allows_redistribution=False,
        review_status=REVIEW_CUSTOMER_ATTESTED if attested else REVIEW_PENDING,
        notes=(
            f"{asset_description}. Owned by the customer. BladeForge stores and renders "
            "it on the customer's instruction and claims no ownership of it. "
            + (
                "The customer confirmed they hold the rights to use it."
                if attested
                else "Awaiting the customer's confirmation that they hold the rights."
            )
        ),
    )


def build_licenses_manifest(
    *,
    blade_model: Any,
    materials_used: tuple[Any, ...],
    defect_profiles: tuple[Any, ...],
    camera_preset: Any,
    environment: Any,
    taxonomy_version: Any,
    extra: tuple[AssetLicense, ...] = (),
) -> dict[str, Any]:
    """Assemble the ``licenses.json`` written into a dataset package."""
    entries: list[AssetLicense] = [
        AssetLicense(
            asset_kind=(
                ASSET_CUSTOMER_MODEL
                if blade_model.source == "customer_import"
                else ASSET_BLADE_MODEL
            ),
            asset_id=blade_model.id,
            asset_version=blade_model.version,
            record=blade_model.license,
            content_checksum=blade_model.checksum,
        ),
        AssetLicense(
            asset_kind=ASSET_CAMERA_PRESET,
            asset_id=camera_preset.id,
            asset_version=camera_preset.version,
            record=camera_preset.license,
            content_checksum=camera_preset.checksum,
        ),
        AssetLicense(
            asset_kind=ASSET_ENVIRONMENT,
            asset_id=environment.id,
            asset_version=environment.version,
            record=environment.license,
            content_checksum=environment.checksum,
        ),
        AssetLicense(
            asset_kind=ASSET_TAXONOMY,
            asset_id=taxonomy_version.id,
            asset_version=taxonomy_version.version,
            record=taxonomy_version.license,
            content_checksum=taxonomy_version.checksum,
        ),
    ]
    entries.extend(
        AssetLicense(
            asset_kind=ASSET_MATERIAL,
            asset_id=material.id,
            asset_version=material.version,
            record=material.license,
            content_checksum=material.checksum,
        )
        for material in materials_used
    )
    entries.extend(
        AssetLicense(
            asset_kind=ASSET_DEFECT_PROFILE,
            asset_id=profile.id,
            asset_version=profile.version,
            record=profile.license,
            content_checksum=profile.checksum,
        )
        for profile in defect_profiles
    )
    entries.extend(extra)

    payload = {
        "schema_version": "1.0.0",
        "statement": (
            "Every asset used to produce this dataset is listed below with its source, "
            "owner, and license. BladeForge claims no ownership of assets marked as "
            "customer-owned; those remain the property of the organisation that "
            "uploaded them."
        ),
        "assets": [entry.as_dict() for entry in entries],
        "unusable_assets": [
            entry.as_dict() for entry in entries if not entry.is_usable
        ],
    }
    payload["checksum_sha256"] = checksum(payload)
    return payload


def assert_all_usable(manifest: dict[str, Any]) -> None:
    """Refuse to publish a dataset containing an asset without cleared rights."""
    unusable = manifest.get("unusable_assets") or []
    if unusable:
        names = ", ".join(f"{a['asset_kind']}:{a['asset_id']}" for a in unusable)
        raise ValueError(
            "These assets are not cleared for use in a deliverable dataset: "
            f"{names}. Each needs an approved license record or a customer rights "
            "confirmation before the dataset can be published."
        )
